import{S as C,i as p}from"./assets/vendor-f33cd494.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();function g(o,e){const i=`https://pixabay.com/api/?${new URLSearchParams({key:"44351431-da99bbc5aa576d6c36cc46a59",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:20,page:e})}`;return fetch(i).then(t=>t.json())}function y(o){return o.map(({webformatURL:e,largeImageURL:s,tags:i,likes:t,views:r,comments:c,downloads:O})=>`
      <a class="gallery-item" href="${s}" >
        <img
          src="${e}"
          alt="${i}" loading='lazy height= 30vh'
        />
      <div class="info">
      <p class="info-item"><b>likes:</b>"${t}"</p>
      <p class="info-item"><b>Views:</b>"${r}"</p>
      <p class="info-item"><b>Comments:</b>"${c}"</p>
      <p class="info-item"><b>Downloads:</b>"${O}"</p>
      </div></a> `).join(" ")}const h="/goit-js-hw-11/assets/alert-icon-40fa32d5.svg",m=document.querySelector(".btn-to-top");window.addEventListener("scroll",b);m.addEventListener("click",L);function b(){const o=window.pageYOffset,e=document.documentElement.clientHeight;o>e&&m.classList.add("visible"),o<e&&m.classList.remove("visible")}function L(){window.pageYOffset>0&&window.scrollTo({top:0,behavior:"smooth"})}const{form:v,gallery:d,loaderBtn:n,textInfo:a}={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loaderBtn:document.querySelector(".js-loader-btn"),textInfo:document.querySelector(".js-text-info")};let u="",l,f,w=new C(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250});b();L();v.addEventListener("submit",S);n.addEventListener("click",B);function S(o){if(o.preventDefault(),window.scrollTo({top:0}),u=o.currentTarget.searchQuery.value.trim(),l=1,d.innerHTML="",n.classList.add("hidden"),u===""){p.warning({message:"The search string cannot be empty. Please specify your search query.",backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16",imageWidth:302,close:!0,closeOnEscape:!0,closeOnClick:!0,progressBar:!0,progressBarColor:"#b51b1b",transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight",theme:"dark",iconUrl:h,iconColor:"#FAFAFB"});return}a.textContent="Loading images, please wait...",a.classList.remove("hidden"),g(u,l).then(e=>{f=20;const s=y(e.hits);if(d.insertAdjacentHTML("beforeend",s),w.refresh(),e.hits.length,e.totalHits>f){const{height:i}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:i-100,behavior:"smooth"}),n.classList.remove("hidden")}else n.classList.add("hidden");e.totalHits===0&&(d.innerHTML="",p.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16",imageWidth:302,close:!0,closeOnEscape:!0,closeOnClick:!0,progressBar:!0,progressBarColor:"#b51b1b",transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight",iconUrl:h,iconColor:"#FAFAFB",theme:"dark"}),n.classList.add("hidden"),a.classList.add("hidden"))}).catch(e=>console.log(e)).finally(()=>{a.classList.add("hidden"),v.reset()})}function B(){l+=1,f=20,g(u,l).then(o=>{const e=y(o.hits);d.insertAdjacentHTML("beforeend",e),w.refresh();const s=Math.ceil(o.totalHits/f);l>s&&(n.classList.add("hidden"),a.textContent="We're sorry, but you've reached the end of search results.",a.classList.remove("hidden"))}).catch(o=>console.log(o))}
//# sourceMappingURL=commonHelpers.js.map
